= Tebako Docker Containers

== What is Tebako?

Tebako is an executable packager designed to simplify the process of packaging applications that rely on an interpretive runtime, making distribution easier.
It packages a set of files into a DwarFS file system for read-only purposes.

For more details, visit the https://www.tebako.org[Tebako website].

== Pre-built Containers

Tebako packages for Linux systems must be created on the same architecture and standard library implementation as the target system. For example:

- **x86_64/aarch64 packages** require **x86_64/aarch64 systems**, respectively.
- Packages compatible with **GNU/musl Linux** must be created in **GNU/musl environments**.

Installing Tebako on different Linux configurations can be cumbersome, and our testing is limited to a specific set of Ubuntu and Alpine configurations.

== Available Container Tags

Tebako containers are available to support packaging for both GNU and musl target environments. The currently available tags are:

=== `ubuntu-20.04`

This container is based on **Ubuntu 20.04 LTS**, providing an environment for packaging applications for GNU systems that use the https://sourceware.org/glibc[`glibc` implementation of the C standard library].

The `--patchelf` option enables the creation of packages that are forward-compatible with GNU Linux distributions running GLIBC version 2.31 and above.

.Minimum versions of GLIBC Linux distributions that support Tebako packages with forward portability
[cols="3", options="header"]
|===
| Distribution | Minimal Supported Version | GLIBC Version
| Ubuntu | 20.04 (Focal Fossa) | GLIBC 2.31
| Debian | 11 (Bullseye) | GLIBC 2.31
| Rocky Linux | 9 | GLIBC 2.34
| Fedora | 33 | GLIBC 2.32
| CentOS | 9 | GLIBC 2.34
| Red Hat Enterprise Linux (RHEL) | 9 | GLIBC 2.34
| Oracle Linux | 9 | GLIBC 2.34
|===

=== `alpine-3.17`

This container is based on **Alpine Linux 3.17**, offering an environment for packaging applications for systems that use the https://musl.libc.org[`musl` implementation of the C standard library].

Both containers are available on the **GitHub Container Registry (GHCR)** for **x86_64 (amd64)** and **aarch64 (arm64)** architectures, with multi-architecture manifests.
These containers come preinstalled with Tebako packaging environments for Ruby versions **3.3.7** and **3.4.1**.

== Using the Tebako Containers

=== General

There are two primary methods for packaging with Tebako:

1. **From outside the container**: Using Docker commands to package your application without entering the container.
2. **From inside the container**: Interactively working within the container to package your application.

=== Prerequisites

- Docker installed on your machine.
- A Ruby application ready for packaging.

=== From Outside the Container

You can package your application from outside the container by running a single Docker command. This command mounts your workspace into the container and executes the `tebako press` command, specifying:

- Application root
- Entry point
- Output location
- Ruby version

[source,sh]
----
$ docker run -v <application_folder>:/mnt/w \
  -t ghcr.io/tamatebako/tebako-${{ container_tag }}:latest \
  tebako press <tebako press parameters>
----

.Packaging the `fontist` Gem from Outside the Container
[example]
====
To package the https://github.com/fontists/fontist[`fontist` gem], a Ruby application for managing fonts, located in the `fontist/` directory under the current working directory, use the following command:

[source,sh]
----
docker run -v $PWD:/mnt/w \
  -t ghcr.io/tamatebako/tebako-ubuntu-20.04:latest \
  tebako press --root=/mnt/w/fontist --entry-point=fontist --output=/mnt/w/fontist-package --Ruby=3.3.7
----
====

=== From Inside the Container

To package your application from inside the Tebako container, follow these steps:

1. Pull the Tebako container image:
+
[source,sh]
----
$ docker pull ghcr.io/tamatebako/tebako-<container_tag>:latest
----
+
Replace `<container_tag>` with the desired container tag (e.g., `ubuntu-20.04` or `alpine-3.17`).

2. Start and enter the container interactively:
+
[source,sh]
----
$ docker run -it --rm -v <application_folder>:/mnt/w ghcr.io/tamatebako/tebako-<container_tag>:latest bash
----
+
Replace `<container_tag>` with the appropriate tag and `<application_folder>` with the path to your application folder.

3. Once inside the container, run the `tebako press` command:
+
[source,sh]
----
$ tebako press <tebako press parameters>
----

.Packaging the `fontist` Gem from Inside the Container
[example]
====
To package the https://github.com/fontists/fontist[`fontist` gem], located in the `fontist/` directory under the current working directory, use the following commands:

[source,sh]
----
# Start and enter the container
$ docker run -it --rm -v $PWD:/mnt/w ghcr.io/tamatebako/tebako-<container_tag>:latest bash

# Run this after entering the container
$ tebako press --root=/mnt/w/fontist --entry-point=fontist --output=/mnt/w/fontist-package --Ruby=3.3.7
----
====

`Gemspec` files often specify the files included in the gem using `git ls-files`. When packaging from inside the container, the container's instance of `git` will be used to resolve these files.

If you use a mounted host directory for packaging, the container's instance of `git` won't be able to use it by default.
To resolve this, you shall alter the container's configuration by running the following command before packaging:

[source,sh]
----
git config --global --add safe.directory <source>
----
(Thanks to https://github.com/bradgessler[bradgessler] for suggestion)

Packaging from inside the container is primarily designed to support CI environments like GitHub Actions (GHA) or Cirrus CI. It provides a complete packaging environment that
does not require any additional installations, making it ideal for automated workflows.

=== Samples

* https://github.com/tamatebako/tebako-ci-containers/blob/main/.github/workflows/build-containers.yml[Tebako CI Containers GitHub Actions workflow]
includes examples featuring packaging of fontist gem.
* https://github.com/tamatebako/tebako-samples[Tebako samples repository] includes tutorial with basic Tebako CI containers examples and advanced workflows that show
how to package Sinatra and Ruby on Rails applications.

== License

Copyright Ribose. All rights reserved.

This work is licensed under the 2-Clause BSD License.
