name: add-tag

on:
  repository_dispatch:
      types: [ 'tebako release' ]

jobs:
  tag:
    name: tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config --global user.name "tebako-ci"
          git config --global user.email "tebako-ci@users.noreply.github.com"

      - name: Create tag
        run: |
          git tag -a v${{ github.event.client_payload.tag }}
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
