name: build-containers

on:
  push:
#    branches: [ main ]
#    paths-ignore:
#      - '**.adoc'
    tags:     [ 'v*' ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  build-containers:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        container:
          - 'ubuntu-20.04'
          - 'alpine-3.17'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: tamatebako
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.container }}.Dockerfile
          push: ${{ contains(github.ref, 'refs/tags/v') }}
          tags: ghcr.io/tamatebako/tebako-${{ matrix.container }}
          labels: |
            latest
            "org.opencontainers.image.source=${{ github.repositoryUrl }}"

      - name: Purge old versions
        if: contains(github.ref, 'refs/tags/v')
        continue-on-error: true
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'tebako-${{ matrix.container }}'
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'